<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>71da3886-bf1f-4e02-bb07-e527aa4f6052</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApiEvent.Application\WebApiEvent.Application.csproj" />
    <ProjectReference Include="..\WebApiEvent.Infrastructure\WebApiEvent.Infrastructure.csproj" />
  </ItemGroup>

</Project>
